/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itenas.oop.project.component;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.oop.project.connection.ConnectionManager;
import org.itenas.oop.project.model.Magang;
import org.itenas.oop.project.repository.ControllerMagang;

/**
 *
 * @author aryan
 */
public class KelolaMagangForm extends javax.swing.JPanel {
    Boolean hasil;
    ControllerMagang conMagang = new ControllerMagang();
    private DefaultTableModel model;
    private ConnectionManager conMan;
    private Connection conn;
    
    public KelolaMagangForm() {
        initComponents();
        model = new DefaultTableModel();
        tabelMagang.setModel(model);
        
        model.addColumn("Judul");
        model.addColumn("Penyelenggara");
        model.addColumn("Lokasi");
        model.addColumn("Tipe");
        model.addColumn("Posisi");
        model.addColumn("Deskripsi");
        model.addColumn("Kualifikasi");
        getData();        
    }
    

    public final void getData(){
        DefaultTableModel dtm = (DefaultTableModel) tabelMagang.getModel();

        dtm.setRowCount(0);

        List<Magang> listMagang = conMagang.showMagang();
        String[] data = new String[8];
        for (Magang newMagang : listMagang){
            data[0] = newMagang.getJudulMagang();
            data[1] = newMagang.getPenyelenggara();
            data[2] = newMagang.getLokasi();
            data[3] = newMagang.getTipeMagang();
            data[4] = newMagang.getPosisiMagang();
            data[5] = newMagang.getDeskripsiMagang();
            data[6] = newMagang.getKualifikasiMagang();
            dtm.addRow(data);
        }
    }
    
    private void clearData(){
        txtJudulPenyelenggara.setText("");
        txtLokasiPenyelenggara.setText("");
        txtPosisiPenyelenggara.setText("");
        txtKualifikasiPenyelenggara.setText("");
        txtKualifikasiPenyelenggara.setText("");
        txtJudulPenyelenggara.setEditable(true);
        txtLokasiPenyelenggara.setEditable(true);
        txtPosisiPenyelenggara.setEditable(true);
        txtKualifikasiPenyelenggara.setEditable(true);
        txtKualifikasiPenyelenggara.setEditable(true);
    }    
 
    private void tampilkanDataMagang(String judulMagang){
        Magang magang = new Magang();
        magang = conMagang.mencariBerdasarkanJudul(judulMagang);
        
        
        DefaultTableModel dtm = (DefaultTableModel) tabelMagang.getModel();
        dtm.setRowCount(0);
        
        if (magang != null){
            String[] data = new String[7];
            data[0] = magang.getJudulMagang();
            data[1] = magang.getPenyelenggara();
            data[2] = magang.getLokasi();
            data[3] = magang.getTipeMagang();
            data[4] = magang.getPosisiMagang();
            data[5] = magang.getDeskripsiMagang();
            data[6] = magang.getKualifikasiMagang();
            dtm.addRow(data);
        }else{
            JOptionPane.showMessageDialog(null,"Barang dengan judul " + judulMagang + " tidak ditemukan!");
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textUsername = new javax.swing.JLabel();
        txtJudulPenyelenggara = new javax.swing.JTextField();
        textUsername1 = new javax.swing.JLabel();
        txtLokasiPenyelenggara = new javax.swing.JTextField();
        textUsername2 = new javax.swing.JLabel();
        txtTipeMagang = new javax.swing.JComboBox<>();
        textUsername3 = new javax.swing.JLabel();
        txtPosisiPenyelenggara = new javax.swing.JTextField();
        textUsername4 = new javax.swing.JLabel();
        textUsername5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        textUsername6 = new javax.swing.JLabel();
        txtSearchJudulMagang = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMagang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsiPenyelenggara = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKualifikasiPenyelenggara = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(239, 236, 229));

        textUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername.setForeground(new java.awt.Color(51, 51, 51));
        textUsername.setText("Judul");

        txtJudulPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtJudulPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtJudulPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtJudulPenyelenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulPenyelenggaraActionPerformed(evt);
            }
        });

        textUsername1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername1.setForeground(new java.awt.Color(51, 51, 51));
        textUsername1.setText("Lokasi");

        txtLokasiPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtLokasiPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtLokasiPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtLokasiPenyelenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiPenyelenggaraActionPerformed(evt);
            }
        });

        textUsername2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername2.setForeground(new java.awt.Color(51, 51, 51));
        textUsername2.setText("Tipe");

        txtTipeMagang.setBackground(new java.awt.Color(239, 239, 239));
        txtTipeMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtTipeMagang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Part Time" }));
        txtTipeMagang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtTipeMagang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipeMagangActionPerformed(evt);
            }
        });

        textUsername3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername3.setForeground(new java.awt.Color(51, 51, 51));
        textUsername3.setText("Posisi");

        txtPosisiPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtPosisiPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtPosisiPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtPosisiPenyelenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosisiPenyelenggaraActionPerformed(evt);
            }
        });

        textUsername4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername4.setForeground(new java.awt.Color(51, 51, 51));
        textUsername4.setText("Deskripsi");

        textUsername5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername5.setForeground(new java.awt.Color(51, 51, 51));
        textUsername5.setText("Kualifikasi");

        btnDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 204, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(51, 51, 51));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 255, 153));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 51, 51));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(51, 51, 51));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(null);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        textUsername6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textUsername6.setForeground(new java.awt.Color(51, 51, 51));
        textUsername6.setText("Pencarian magang berdasarkan judul");

        txtSearchJudulMagang.setBackground(new java.awt.Color(239, 239, 239));
        txtSearchJudulMagang.setForeground(new java.awt.Color(51, 51, 51));
        txtSearchJudulMagang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtSearchJudulMagang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchJudulMagangActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tabelMagang.setBackground(new java.awt.Color(239, 239, 239));
        tabelMagang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Judul", "Penyelenggara", "Lokasi", "Tipe", "Posisi", "Deskripsi", "Kualifikasi"
            }
        ));
        tabelMagang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMagangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMagang);

        txtDeskripsiPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtDeskripsiPenyelenggara.setColumns(20);
        txtDeskripsiPenyelenggara.setForeground(new java.awt.Color(191, 191, 191));
        txtDeskripsiPenyelenggara.setRows(5);
        txtDeskripsiPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        jScrollPane2.setViewportView(txtDeskripsiPenyelenggara);

        txtKualifikasiPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtKualifikasiPenyelenggara.setColumns(20);
        txtKualifikasiPenyelenggara.setRows(5);
        txtKualifikasiPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        jScrollPane3.setViewportView(txtKualifikasiPenyelenggara);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLokasiPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJudulPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textUsername3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosisiPenyelenggara)
                            .addComponent(textUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipeMagang, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textUsername6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchJudulMagang, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textUsername5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJudulPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUsername1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLokasiPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textUsername2)
                        .addGap(3, 3, 3)
                        .addComponent(txtTipeMagang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUsername3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPosisiPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textUsername4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textUsername5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(textUsername6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchJudulMagang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulPenyelenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulPenyelenggaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulPenyelenggaraActionPerformed

    private void txtLokasiPenyelenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiPenyelenggaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiPenyelenggaraActionPerformed

    private void txtTipeMagangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipeMagangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipeMagangActionPerformed

    private void txtPosisiPenyelenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosisiPenyelenggaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosisiPenyelenggaraActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int i = tabelMagang.getSelectedRow();

        String judulMagang = tabelMagang.getModel().getValueAt(i, 0).toString();
        conMagang.deleteMagang(judulMagang);
        getData();
        clearData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
        getData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int i = tabelMagang.getSelectedRow();

        if (i == -1){
            JOptionPane.showMessageDialog(btnUpdate, "Harap pilih salah satu data", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String judulMagang = tabelMagang.getModel().getValueAt(i, 0).toString();
        String penyelenggara = tabelMagang.getModel().getValueAt(i, 1).toString();
        String lokasi = tabelMagang.getModel().getValueAt(i, 2).toString();
        String tipeMagang = tabelMagang.getModel().getValueAt(i, 3).toString();
        String posisiMagang = tabelMagang.getModel().getValueAt(i, 4).toString();
        String deskripsiMagang = tabelMagang.getModel().getValueAt(i, 5).toString();
        String kualifikasiMagang = tabelMagang.getModel().getValueAt(i, 6).toString();

        String newJudul = txtJudulPenyelenggara.getText();
        String newLokasi = txtLokasiPenyelenggara.getText();
        String newTipe = (String)txtTipeMagang.getSelectedItem();
        String newPosisi = txtPosisiPenyelenggara.getText();
        String newDeskripsi = txtKualifikasiPenyelenggara.getText();
        String newKualifikasi = txtKualifikasiPenyelenggara.getText();

        hasil = conMagang.updateMagang(newJudul, penyelenggara, newLokasi, newTipe, newPosisi, newDeskripsi, newKualifikasi, judulMagang);
        getData();
        clearData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        hasil = conMagang.insertMagang(txtJudulPenyelenggara.getText(), txtLokasiPenyelenggara.getText(), (String)txtTipeMagang.getSelectedItem(), txtPosisiPenyelenggara.getText(), txtKualifikasiPenyelenggara.getText(), txtKualifikasiPenyelenggara.getText());
        if (hasil){
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            getData();
            clearData();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan", " Pesan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtSearchJudulMagangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchJudulMagangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchJudulMagangActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String judulMagang = txtSearchJudulMagang.getText();
            tampilkanDataMagang(judulMagang);

        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Anda Salah Memasukkan Judul!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tabelMagangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMagangMouseClicked
        int i = tabelMagang.getSelectedRow();

        TableModel model = tabelMagang.getModel();

        txtJudulPenyelenggara.setText(model.getValueAt(i, 0).toString());
        txtLokasiPenyelenggara.setText(model.getValueAt(i, 2).toString());
        txtTipeMagang.setSelectedItem(model.getValueAt(i, 3).toString());
        txtPosisiPenyelenggara.setText(model.getValueAt(i, 4).toString());
        txtKualifikasiPenyelenggara.setText(model.getValueAt(i, 5).toString());
        txtKualifikasiPenyelenggara.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tabelMagangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelMagang;
    private javax.swing.JLabel textUsername;
    private javax.swing.JLabel textUsername1;
    private javax.swing.JLabel textUsername2;
    private javax.swing.JLabel textUsername3;
    private javax.swing.JLabel textUsername4;
    private javax.swing.JLabel textUsername5;
    private javax.swing.JLabel textUsername6;
    private javax.swing.JTextArea txtDeskripsiPenyelenggara;
    private javax.swing.JTextField txtJudulPenyelenggara;
    private javax.swing.JTextArea txtKualifikasiPenyelenggara;
    private javax.swing.JTextField txtLokasiPenyelenggara;
    private javax.swing.JTextField txtPosisiPenyelenggara;
    private javax.swing.JTextField txtSearchJudulMagang;
    private javax.swing.JComboBox<String> txtTipeMagang;
    // End of variables declaration//GEN-END:variables
}
