/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itenas.oop.project.component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.oop.project.connection.ConnectionManager;
/**
 *
 * @author aryan
 */
public class MelihatDaftarPenyelenggara extends javax.swing.JPanel {

    /**
     * Creates new form KelolaMagangForm
     */
    public MelihatDaftarPenyelenggara() {
        initComponents();
        tableDataPenyelenggara();
        
        txtSearchNamaPenyelenggara.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cariTableDataPenyelenggara(txtSearchNamaPenyelenggara.getText());
        }
    }
});
    }
    
    private void tableDataPenyelenggara() {
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.connectDb();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Penyelenggara");
        model.addColumn("Nama");
        model.addColumn("Instansi");
        model.addColumn("Username");
        tablePenyelenggara.setModel(model);

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT id_penyelenggara, nama, instansi, username FROM daftarpenyelenggara";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_penyelenggara"),
                    rs.getString("nama"), 
                    rs.getString("instansi"),
                    rs.getString("username"),
                });
            }
            tablePenyelenggara.setModel(model);
            conMan.disconnectDb(conn);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }
    
    private void cariTableDataPenyelenggara(String namaPenyelenggara) {
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.connectDb();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Penyelenggara");
        model.addColumn("Nama");
        model.addColumn("Instansi");
        model.addColumn("Username");
        tablePenyelenggara.setModel(model);

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT id_penyelenggara, nama, instansi, username FROM penyelenggara WHERE nama LIKE '%" + namaPenyelenggara + "%'";
            ResultSet rs = stmt.executeQuery(query);
            boolean hasil = false;

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_penyelenggara"),
                    rs.getString("nama"), 
                    rs.getString("instansi"),
                    rs.getString("username"),
                });
                hasil = true;
            }
            if (!hasil) {
                JOptionPane.showMessageDialog(this, "Nama Penyelenggara tidak ditemukan!", "Pencarian Tidak Ditemukan", JOptionPane.INFORMATION_MESSAGE);
            }
            tablePenyelenggara.setModel(model);
            conMan.disconnectDb(conn);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenyelenggara = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        txtSearchNamaPenyelenggara = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 236, 229));

        jPanel2.setBackground(new java.awt.Color(56, 116, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(494, 146));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("DAFTAR PENYELENGGARA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tablePenyelenggara.setBackground(new java.awt.Color(46, 80, 119));
        tablePenyelenggara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenyelenggara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenyelenggaraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenyelenggara);

        btnHapus.setBackground(new java.awt.Color(184, 0, 31));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtSearchNamaPenyelenggara.setBackground(new java.awt.Color(239, 239, 239));
        txtSearchNamaPenyelenggara.setForeground(new java.awt.Color(51, 51, 51));
        txtSearchNamaPenyelenggara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 191, 191), 1, true));
        txtSearchNamaPenyelenggara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNamaPenyelenggaraActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchNamaPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchNamaPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablePenyelenggaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenyelenggaraMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablePenyelenggaraMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int pilihBaris = tablePenyelenggara.getSelectedRow();
        if (pilihBaris == -1) {
            JOptionPane.showMessageDialog(btnHapus, "Harap pilih data untuk dihapus!","Warning",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nama = tablePenyelenggara.getValueAt(pilihBaris, 1).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,"Apakah Anda yakin ingin menghapus penyelenggara dengan nama: " + nama + "?",
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            ConnectionManager conMan = new ConnectionManager();
            Connection conn = conMan.connectDb();
            try {
                Statement stmt = conn.createStatement();
                String query = "DELETE FROM penyelenggara WHERE nama = '" + nama + "'";
                int barisHapus = stmt.executeUpdate(query);

                if (barisHapus > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus.");
                }
            } catch (SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.");
            } finally {
                conMan.disconnectDb(conn);
            }
            tableDataPenyelenggara();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchNamaPenyelenggaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNamaPenyelenggaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNamaPenyelenggaraActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String namaPenyelenggara = txtSearchNamaPenyelenggara.getText();
            if (namaPenyelenggara.isEmpty()) {
                cariTableDataPenyelenggara("");
            } else {
                cariTableDataPenyelenggara(namaPenyelenggara);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nama Admin yang anda masukan tidak ada " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePenyelenggara;
    private javax.swing.JTextField txtSearchNamaPenyelenggara;
    // End of variables declaration//GEN-END:variables
}
